<!-- Flex Filter and Order -->
<div class="d-flex bd-highlight mb-2">
    <div class="bd-highlight me-2">
        <!-- Order Dropdown -->
        <div class="dropdown">
            <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1"
                    data-bs-toggle="dropdown" aria-expanded="false">
                Order Table By...
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
                <li><a class="dropdown-item" href="#">Order by ID - Ascending</a></li>
                <li><a class="dropdown-item" href="#">Order by ID - Descending</a></li>
                <li><a class="dropdown-item" href="#">Order by Status - Ascending</a></li>
                <li><a class="dropdown-item" href="#">Order by Status - Descending</a></li>
            </ul>
        </div>
    </div>
    <!-- Filter Dropdown -->
    <div class="dropdown">
        <button class="btn btn-dark dropdown-toggle" type="button" id="dropdownMenuButton1"
                data-bs-toggle="dropdown" aria-expanded="false">
            Filter Table By...
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
            <li><a class="dropdown-item" href="#">Only Pending Deliveries</a></li>
            <li><a class="dropdown-item" href="#">Only Shipped Deliveries</a></li>
            <li><a class="dropdown-item" href="#">Only Out for Delivery Deliveries</a></li>
            <li><a class="dropdown-item" href="#">Only Delivered Deliveries</a></li>
        </ul>
    </div>
</div>