<?php if ($_SESSION['user']['currentTable'] == "Deliveries"): ?>
    <!-- Search form -->
    <div class="flex-grow-1">
        <form action="/" method="POST">
            <input type="hidden" name="_method" value="SEARCH">
            <div>
                <input type="text" class="form-control" id="searchInput" name="search" placeholder="Search for Parcel">
            </div>
        </form>
    </div>
<?php endif; ?>

<?php if ($_SESSION['user']['currentTable'] == "Users"): ?>
    <!-- Search form -->
    <div class="col-md-3 mb-1">
        <form action="/" method="POST">
            <input type="hidden" name="_method" value="SEARCH">
            <div class="input-group">
                <input type="text" class="form-control" id="searchInput" name="search" placeholder="Search for Parcel">
                <div class="input-group-append">
                    <button class="btn btn-outline-dark" type="submit">Search</button>
                </div>
            </div>
            <!-- Labels and checkboxes -->
            <div class="mt-2">
                <div class="d-flex flex-wrap">
                    <div class="col-sm-6 col-md-3 mb-2">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="userID" name="userID"
                                   value="userID">
                            <label class="form-check-label" for="userID">Search by ID</label>
                        </div>
                    </div>
                    <div class="col-sm-6 col-md-3 mb-2">
                        <div class="form-check form-switch">
                            <input class="form-check-input" type="checkbox" id="username" name="username"
                                   value="username">
                            <label class="form-check-label" for="username">Search by Username</label>
                        </div>
                    </div>
                </div>
            </div>
        </form>
    </div>
<?php endif; ?>
