<!-- Status Dynamic Modal -->
<div class="modal fade" id="pendingModal" tabindex="-1" aria-labelledby="pendingModalLabel" aria-hidden="true">
    <!-- Modal content for Pending -->
    <div class="modal-dialog">
        <div class="modal-content">
            <!-- Your modal content for "Pending" -->
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLabel">Parcel Status Change</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Are you sure you want to change the status of Parcel with ID: <strong>1</strong>, to <strong></strong> </p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Confirm Change</button>
            </div>
        </div>
    </div>
</div>
