<?php require('Views/partials/head.phtml') ?>
<?php require('Views/partials/nav.phtml') ?>
<?php require('Views/partials/header.phtml') ?>
<?php $_SESSION['user']['searched'] = false ?>

<!-- Deliverer View -->
<?php if ($_SESSION['user']['usertypename'] == "Deliverer"): ?>
<div id="main-content">
    <div class="mt-2 m-4">
        <h1><?= $_SESSION['user']['username'] ?>'s Deliveries</h1>
        <button id="loadMapButton">Press button to load the map with deliveries</button>
        <div id="map" class="hide"></div>
        <script src="Views/api/js/loadMap.js"></script>
        <h4>Statistics:</h4>

        <div>
            <!-- Statistics Section -->
            <section class="table table-responsive">
                <form method="POST" action="/">
                    <table class="table border-dark table-bordered table-grey table-striped">
                        <thead>
                        <tr>
                            <th scope="col">
                                <div class="d-flex justify-content-between align-items-center">
                                    <span>Total Deliveries</span>
                                    <button type="submit" name="show_deliveries" value="show_deliveries"
                                            class="btn btn-sm btn-danger">
                                        Show All Deliveries
                                    </button>
                                </div>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><?= count($view->totalDeliveries) ?></td>
                        </tr>
                        </tbody>
                    </table>
                </form>
            </section>

            <?php if ($_SESSION['user']['currentTable'] == 'Deliveries'): ?>
                <div class="container-fluid px-0">
                    <div class="row row-cols-sm-2 row-cols-md-3 row-cols-lg-4 mx-0">
                        <?php foreach ($view->currentItems as $deliveryPointData) : ?>
                            <div class="col px-3 mb-4">
                                <div class="delivery-point">
                                    <div class="delivery-point-header">
                                        <h5><?= $deliveryPointData->getPointName() ?></h5>
                                        <button id="show-on-<?= $deliveryPointData->getPointId() ?>" class="status show-on-map" data-lat="<?= $deliveryPointData->getPointLat() ?>" data-lng="<?= $deliveryPointData->getPointLng() ?>">Show on Map</button>
                                        <span class="status"><?= htmlspecialchars($deliveryPointData->getPointStatus()) ?></span>
                                    </div>
                                    <div class="delivery-point-body">
                                        <p><strong>ID:</strong> <?= $deliveryPointData->getPointId() ?></p>
                                        <p><strong>Address:</strong> <?= $deliveryPointData->getPointAddress1() ?>, <?= $deliveryPointData->getPointAddress2() ?>, <?= $deliveryPointData->getPointPostcode() ?></p>
                                        <p><strong>Coordinates:</strong> <?= htmlspecialchars($deliveryPointData->getPointLat()) ?> / <?= htmlspecialchars($deliveryPointData->getPointLng()) ?></p>
                                        <?php if (htmlspecialchars($deliveryPointData->getPointDelPhoto())) : ?>
                                            <div class="delivery-photo">
                                                <img src="images/<?= htmlspecialchars($deliveryPointData->getPointDelPhoto()) ?>" alt="Delivery Photo" class="img-fluid">
                                            </div>
                                        <?php else : ?>
                                            <p>Only delivered parcels have pictures!</p>
                                        <?php endif; ?>
                                    </div>
                                </div>
                            </div>
                        <?php endforeach; ?>
                    </div>
                    <div class="row">
                        <div class="col-12">
                            <?php require_once('Views/partials/pagination.phtml') ?>
                        </div>
                    </div>
                </div>
    <?php endif; ?>
    <?php endif; ?>


    <?php require('Views/partials/footer.phtml') ?>
