<?php require('Views/partials/head.phtml') ?>
<?php require('Views/partials/nav.phtml') ?>
<?php require('Views/partials/header.phtml') ?>

<?php if ($_SESSION['user']['usertypename'] == "Deliverer"): ?>
<div id="main-content">
    <div class="mt-2 m-4">
        <h1><?= $_SESSION['user']['username'] ?>'s Deliveries</h1>

        <div>
            <?php require_once('Views/partials/searchForm.phtml') ?>
            <?php require_once('Views/partials/filterAndOrder.phtml') ?>

            <!-- Table -->
            <div class="table table-responsive">
                <table class="table border-dark table-bordered table-grey table-striped">
                    <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Address1</th>
                        <th scope="col">Address2</th>
                        <th scope="col">Postcode</th>
                        <th scope="col">
                            Status
                            <i class="bi bi-info-circle"></i>
                        </th>
                        <?php if ($_SESSION['user']['usertypename'] == 'Manager'): ?>
                            <th scope="col">Actions</th>
                        <?php endif; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($currentItems as $deliveryPointData) : ?>
                        <tr>
                            <th scope="row"><?= $deliveryPointData->getPointId(); ?></th>
                            <td><?= $deliveryPointData->getPointName(); ?></td>
                            <td><?= $deliveryPointData->getPointAddress1(); ?></td>
                            <td><?= $deliveryPointData->getPointAddress2(); ?></td>
                            <td><?= $deliveryPointData->getPointPostcode(); ?></td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary dropdown-toggle"
                                            data-bs-toggle="dropdown"
                                            aria-expanded="false">
                                        <?php
                                        if ($deliveryPointData->getPointStatus() == '1') {
                                            echo 'Pending';
                                        } else if ($deliveryPointData->getPointStatus() == '2') {
                                            echo 'Shipped';
                                        } else if ($deliveryPointData->getPointStatus() == '3') {
                                            echo 'Out for delivery';
                                        } else if ($deliveryPointData->getPointStatus() == '4') {
                                            echo 'Delivered';
                                        }
                                        ?>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <?php if ($deliveryPointData->getPointStatus() == '1'): ?>
                                            <li><a class="dropdown-item dropdown-menu-dark disabled" href="#">Pending
                                                    parcels status can't be changed by a deliverer!</a></li>
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                            <li><a class="dropdown-item disabled border-bottom" href="#">Mark as:
                                                    Shipped</a></li>
                                            <li><a class="dropdown-item disabled border-bottom" href="#">Mark as: Out
                                                    for
                                                    delivery</a></li>
                                            <li><a class="dropdown-item disabled" href="#">Mark as: Delivered</a></li>
                                        <?php else: ?>
                                            <li><a class="dropdown-item border-bottom" href="#">Mark as: Shipped</a>
                                            </li>
                                            <li><a class="dropdown-item border-bottom" href="#">Mark as: Out for
                                                    delivery</a></li>
                                            <li><a class="dropdown-item" href="#">Mark as: Delivered</a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>

            <?php require_once('Views/partials/pagination.phtml') ?>
        </div>
    </div>
    <?php endif; ?>

    <?php if ($_SESSION['user']['usertypename'] == "Manager"): ?>
    <div id="main-content">
        <div class="mt-2 m-4">
            <h2>Admin Panel</h2>
            <h4>Statistics:</h4>

            <section class="table table-responsive">
                <form method="POST" action="/">
                    <input type="hidden" name="_currentItems" value="<?= $currentItems ?>">
                    <table class="table border-dark table-bordered table-grey table-striped">
                        <thead>
                        <tr>
                            <th scope="col">
                                <div class="d-flex justify-content-between align-items-center">
                                    <span>Total Deliveries</span>
                                    <button type="submit" name="show_deliveries" value="show"
                                            class="btn btn-sm btn-danger">
                                        Show All Deliveries
                                    </button>
                                </div>
                            </th>
                            <th scope="col">
                                <div class="d-flex justify-content-between align-items-center">
                                    <span>Total Deliverers</span>
                                    <button type="submit" name="show_deliverers" value="show"
                                            class="btn btn-sm btn-danger">
                                        Show All Deliverers
                                    </button>
                                </div>
                            </th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td><?= count($view->deliveryPointDataSet) ?></td>
                            <td><?= count($view->deliveryUserDataSet) ?></td>
                        </tr>
                        </tbody>
                    </table>
                </form>


                <table class="table border-dark table-bordered table-grey table-striped">
                    <thead>
                    <tr>
                        <th scope="col">Total "Pending" Deliveries</th>
                        <th scope="col">Total "Shipped" Deliveries</th>
                        <th scope="col">Total "Out For Delivery" Deliveries</th>
                        <th scope="col">Total "Delivered" Deliveries</th>
                    </tr>
                    </thead>
                    <tbody>
                    <tr>
                        <td>5</td>
                        <td>5</td>
                        <td>5</td>
                        <td>5</td>
                    </tr>
                    </tbody>
                </table>
            </section>

            <!-- Table -->
            <div class="table table-responsive">
                <table class="table border-dark table-bordered table-grey table-striped">
                    <thead class="table-dark">
                    <tr>
                        <th scope="col">ID</th>
                        <th scope="col">Name</th>
                        <th scope="col">Address1</th>
                        <th scope="col">Address2</th>
                        <th scope="col">Postcode</th>
                        <th scope="col">
                            Status
                            <i class="bi bi-info-circle"></i>
                        </th>
                        <?php if ($_SESSION['user']['usertypename'] == 'Manager'): ?>
                            <th scope="col">Actions</th>
                        <?php endif; ?>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($currentItems as $deliveryPointData) : ?>
                        <tr>
                            <th scope="row"><?= $deliveryPointData->getPointId(); ?></th>
                            <td><?= $deliveryPointData->getPointName(); ?></td>
                            <td><?= $deliveryPointData->getPointAddress1(); ?></td>
                            <td><?= $deliveryPointData->getPointAddress2(); ?></td>
                            <td><?= $deliveryPointData->getPointPostcode(); ?></td>
                            <td>
                                <div class="btn-group">
                                    <button type="button" class="btn btn-primary dropdown-toggle"
                                            data-bs-toggle="dropdown"
                                            aria-expanded="false">
                                        <?php
                                        if ($deliveryPointData->getPointStatus() == '1') {
                                            echo 'Pending';
                                        } else if ($deliveryPointData->getPointStatus() == '2') {
                                            echo 'Shipped';
                                        } else if ($deliveryPointData->getPointStatus() == '3') {
                                            echo 'Out for delivery';
                                        } else if ($deliveryPointData->getPointStatus() == '4') {
                                            echo 'Delivered';
                                        }
                                        ?>
                                    </button>
                                    <ul class="dropdown-menu">
                                        <?php if ($deliveryPointData->getPointStatus() == '1'): ?>
                                            <li><a class="dropdown-item dropdown-menu-dark disabled" href="#">Pending
                                                    parcels status can't be changed by a deliverer!</a></li>
                                            <li>
                                                <hr class="dropdown-divider">
                                            </li>
                                            <li><a class="dropdown-item disabled border-bottom" href="#">Mark as:
                                                    Shipped</a></li>
                                            <li><a class="dropdown-item disabled border-bottom" href="#">Mark as: Out
                                                    for
                                                    delivery</a></li>
                                            <li><a class="dropdown-item disabled" href="#">Mark as: Delivered</a></li>
                                        <?php else: ?>
                                            <li><a class="dropdown-item border-bottom" href="#">Mark as: Shipped</a>
                                            </li>
                                            <li><a class="dropdown-item border-bottom" href="#">Mark as: Out for
                                                    delivery</a></li>
                                            <li><a class="dropdown-item" href="#">Mark as: Delivered</a></li>
                                        <?php endif; ?>
                                    </ul>
                                </div>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
            </div>
            <?php endif; ?>

            <?php require('Views/partials/footer.phtml') ?>
