<?php require('Views/partials/head.phtml') ?>
<?php require('Views/partials/nav.phtml') ?>
<?php require('Views/partials/header.phtml') ?>

    <!-- Manager View -->
    <?php if ($_SESSION['user']['usertypename'] == "Manager"): ?>
    <div id="main-content">
        <div class="mt-2 m-4">
            <h2>Admin Panel</h2>
            <h4>Statistics:</h4>
            <div>
                <!-- Statistics Section -->
                <section class="table table-responsive">
                    <form method="POST" action="/">
                        <table class="table border-dark table-bordered table-grey table-striped">
                            <thead>
                            <tr>
                                <th scope="col">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <span>Total Deliveries</span>
                                        <button type="submit" name="show_deliveries" value="show"
                                                class="btn btn-sm btn-danger">
                                            Show All Deliveries
                                        </button>
                                    </div>
                                </th>
                                <th scope="col">
                                    <div class="d-flex justify-content-between align-items-center">
                                        <span>Total Deliverers</span>
                                        <button type="submit" name="show_deliverers" value="show"
                                                class="btn btn-sm btn-danger">
                                            Show All Deliverers
                                        </button>
                                    </div>
                                </th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td><?= count($view->totalDeliveries) ?></td>
                                <td><?= count($view->totalDeliverers) ?></td>
                            </tr>
                            </tbody>
                        </table>
                    </form>
                    <table class="table border-dark table-bordered table-grey table-striped">
                        <thead>
                        <tr>
                            <th scope="col">Total "Pending" Deliveries</th>
                            <th scope="col">Total "Shipped" Deliveries</th>
                            <th scope="col">Total "Out For Delivery" Deliveries</th>
                            <th scope="col">Total "Delivered" Deliveries</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>5</td>
                            <td>5</td>
                            <td>5</td>
                            <td>5</td>
                        </tr>
                        </tbody>
                    </table>
                </section>

                <!-- Deliveries Table -->
                <?php if ($_SESSION['user']['currentTable'] == 'Deliveries'): ?>
                    <?php require_once('Views/partials/searchForm.phtml') ?>
                    <?php require_once('Views/partials/filterAndOrder.phtml') ?>
                    <div class="table table-responsive">
                        <table class="table border-dark table-bordered table-grey table-striped">
                            <thead class="table-dark">
                            <tr>
                                <th scope="col">ID</th>
                                <th scope="col">Name</th>
                                <th scope="col">Address1</th>
                                <th scope="col">Address2</th>
                                <th scope="col">Postcode</th>
                                <th scope="col">
                                    Status
                                    <i class="bi bi-info-circle"></i>
                                </th>
                                <th scope="col">Actions</th>
                            </tr>
                            <!-- Status -->
                            </thead>
                            <tbody>
                            <?php foreach ($view->totalDeliveries as $deliveryPointData) : ?>
                                <tr>
                                    <th scope="row"><?= $deliveryPointData->getPointId() ?></th>
                                    <td><?= $deliveryPointData->getPointName() ?></td>
                                    <td><?= $deliveryPointData->getPointAddress1() ?></td>
                                    <td><?= $deliveryPointData->getPointAddress2() ?></td>
                                    <td><?= $deliveryPointData->getPointPostcode() ?></td>
                                    <td>
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-primary dropdown-toggle"
                                                    data-bs-toggle="dropdown"
                                                    aria-expanded="false">
                                                <?php
                                                if ($deliveryPointData->getPointStatus() == '1') {
                                                    echo 'Pending';
                                                } else if ($deliveryPointData->getPointStatus() == '2') {
                                                    echo 'Shipped';
                                                } else if ($deliveryPointData->getPointStatus() == '3') {
                                                    echo 'Out for delivery';
                                                } else if ($deliveryPointData->getPointStatus() == '4') {
                                                    echo 'Delivered';
                                                }
                                                ?>
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as:
                                                        "Pending"</a>
                                                </li>
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as:
                                                        "Shipped"</a>
                                                </li>
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as: "Out for
                                                        delivery"</a></li>
                                                <li><a class="dropdown-item" href="#">Mark as: "Delivered"</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                    <td>
                                        <!-- Actions -->
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-danger dropdown-toggle"
                                                    data-bs-toggle="dropdown"
                                                    aria-expanded="false">
                                                Edit Parcel:
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as: Pending</a>
                                                </li>
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as: Shipped</a>
                                                </li>
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as: Out for
                                                        delivery</a></li>
                                                <li><a class="dropdown-item" href="#">Mark as: Delivered</a></li>
                                                <hr class="dropdown-divider">
                                                <li><a class="dropdown-item" href="#">Assign Deliverer</a></li>
                                                <li><a class="dropdown-item border" href="#">Edit Delivery Item</a></li>
                                                <li><a class="dropdown-item" href="#">Delete Delivery Item</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                                <?php require_once('Views/partials/pagination.phtml') ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>

                    <!-- Deliverers Table -->
                <?php elseif ($_SESSION['user']['currentTable'] == 'Deliverers'): ?>
                    <?php require_once('Views/partials/searchForm.phtml') ?>
                    <?php require_once('Views/partials/filterAndOrder.phtml') ?>
                    <div class="table table-responsive">
                        <table class="table border-dark table-bordered table-grey table-striped">
                            <thead class="table-dark">
                            <tr>
                                <th scope="col">User ID</th>
                                <th scope="col">Username</th>
                                <th scope="col">UserType</th>
                                <th scope="col">Actions</th>
                            </tr>
                            <!-- Status -->
                            </thead>
                            <tbody>
                            <?php foreach ($view->deliveriesTable as $deliveryUserData) : ?>
                                <tr>
                                    <th scope="row"><?= $deliveryUserData->getUserID() ?></th>
                                    <td><?= $deliveryUserData->getUserUsername() ?></td>
                                    <td>
                                        <?php
                                        if ($deliveryUserData->getUserUserType() == 1) {
                                            echo 'Table';
                                        } else if ($deliveryUserData->getUserUserType() == 2) {
                                            echo 'Deliverer';
                                        }
                                        ?>
                                    </td>
                                    <td>
                                        <!-- Actions -->
                                        <div class="btn-group">
                                            <button type="button" class="btn btn-danger dropdown-toggle"
                                                    data-bs-toggle="dropdown"
                                                    aria-expanded="false">
                                                Edit User:
                                            </button>
                                            <ul class="dropdown-menu">
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as: Pending</a>
                                                </li>
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as: Shipped</a>
                                                </li>
                                                <li><a class="dropdown-item border-bottom" href="#">Mark as: Out for
                                                        delivery</a></li>
                                                <li><a class="dropdown-item" href="#">Mark as: Delivered</a></li>
                                                <hr class="dropdown-divider">
                                                <li><a class="dropdown-item" href="#">Assign Deliverer</a></li>
                                                <li><a class="dropdown-item border" href="#">Edit Delivery Item</a></li>
                                                <li><a class="dropdown-item" href="#">Delete Delivery Item</a></li>
                                            </ul>
                                        </div>
                                    </td>
                                </tr>
                                <?php require_once('Views/partials/pagination.phtml') ?>
                            <?php endforeach; ?>
                            </tbody>
                        </table>
                    </div>
                <?php endif; ?>
                <?php endif; ?>
            </div>

            <?php require('Views/partials/footer.phtml') ?>
